### PR TITLE
Update package.json dependencies for Node 4+

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Comment by denisborovikov** [comment]
Unfortunately, sprity has no backward compatibility with css-sprite and processing of retina sprites in `gulp sprites` task have to be rewritten. Now it works incorrectly and produces one sprite with normal and retina images instead of two.

**Comment by chicoxyzzy** [comment]
OK. I'll try to fix it later

**Comment by chicoxyzzy** [comment]
I think we can just fork https://github.com/aslansky/css-sprite and update lwip dep there to 0.0.8. I have no time to check this solution but I believe it should fix building lwip for node 4+

**Comment by denisborovikov** [comment]
My opinion is to rewrite gulp task is more preferable than "just" fork and support custom library. But it could be temporary workaround if you already have troubles compiling styles. 

I started rewriting couple of times but never finished.

**Comment by chicoxyzzy** [comment]
it is deprecated anyway so no one supports that library about few months already :) fork could be temporary solution to make things work on modern versions of node before task will be rewritten

**Pull request closed without merging**
